header:
  schema-version: 2.0.0
  last-updated: '2025-01-01'
  last-reviewed: '2025-01-01'
  url: https://github.com/sangramrath/meshery/blob/security-slam-kubecon-2025-eu/.github/security-insights.yml
  comment: |
    This file contains the security insights information for the Meshery project.

project:
  name: meshery
  administrators:
    - name: Sangram Rath 
      affiliation: Meshery
      email: sangram.rath@gmail.com
      social: 
      primary: true
  repositories:
    - name: meshery
      url: https://github.com/sangramrath/meshery
      comment: |
        Meshery.
  vulnerability-reporting:
    reports-accepted: true
    bug-bounty-available: false
